stages:

- stage: ${{ parameters.azdoEnv }}
  displayName: ${{ parameters.azdoEnv }}
  dependsOn: []
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.branch }}'))

  variables:
  - name: buildConfiguration
    value: '${{ parameters.buildConfiguration }}'
    readonly: true

  - name: buildPlatform
    value: '${{ parameters.buildPlatform }}'
    readonly: true

  - name: siteName
    value: '${{ parameters.siteName }}'
    readonly: true

  jobs:

  # Build

  - job: build
    displayName: 'build and package'
    pool:
      vmImage: windows-latest # for list, see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
    workspace:
      clean: all # Options: outputs, resources, all
    steps:
    - template: 'hearye-client-tasks-build.yml'

# Deploy

  - deployment: deploy
    displayName: 'deploy client'
    dependsOn: build
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.azdoEnv }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'hearye-client-tasks-deploy.yml'
            parameters:
              azureSubscription: ${{ parameters.azureSubscription }} # AzDO will not allow a variable for this field in the task
              