name: $(SourceBranchName)-client-$(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
  - repository: self
    type: git
    name: self
  - repository: BWA
    type: git
    name: BWA
    trigger:
      branches:
        include:
        - main
      paths:
        include:
        - 'Server/*'

variables:
- name: projectName
  value: 'hearye' # Example: 'hearye'
  readonly: true

- name: projectFile
  value: '**/BWA/Server/*.csproj'
  readonly: true

- name: solution
  value: '**/BWA/*.sln'
  readonly: true

- name: artifactName
  value: '$(Build.SourceBranchName)-drop' # do not adjust unless required
  readonly: true

- name: system.debug
  value: false
        
stages:

# Dev
#- template: 'hearye-client-stages.yml'
#  parameters:
#    branch: 'dev'
#    azdoEnv: 'Dev'
#    buildConfiguration: 'debug'
#    buildPlatform: 'any cpu'
#    azureSubscription: 'Azure-Dev'
#    siteName: '$(project)-dev-web'

# Test
#- template: 'webApp-stages.yml'
#  parameters:
#    branch: 'test'
#    azdoEnv: 'Test'
#    buildConfiguration: 'release'
#    buildPlatform: 'any cpu'
#    azureSubscription: 'Azure-Test'
#    siteName: '$(project)-test-web'

# Production
- template: 'hearye-server-stages.yml'
  parameters:
    branch: 'main'
    azdoEnv: 'Production'
    buildConfiguration: 'release'
    buildPlatform: 'any cpu'
    buildId: $(Build.BuildId)
    apiName: '$(projectName)-api'
    azureSubscription: 'stephan-hearye-sc'
    dockerRegistry: 'stephan-dockerhub-sc'
    kvName: '$(projectName)-kv'
    resourceGroup: '$(projectName)'