stages:

- stage: ${{ parameters.azdoEnv }}
  displayName: ${{ parameters.azdoEnv }}
  dependsOn: []
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.branch }}'))

  variables:
  - name: buildConfiguration
    value: '${{ parameters.buildConfiguration }}'
    readonly: true

  - name: buildPlatform
    value: '${{ parameters.buildPlatform }}'
    readonly: true

  - name: siteName
    value: '${{ parameters.siteName }}'
    readonly: true

  jobs:

  # Build

  - job: build
    displayName: 'build docker image and push'
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest' # for list, see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
    workspace:
      clean: all # Options: outputs, resources, all
    steps:
    - template: 'hearye-server-tasks-build.yml'
      parameters: 
        buildId: ${{ parameters.buildId }}
        dockerRegistry: ${{ parameters.dockerRegistry }}

# Deploy

  - deployment: deploy
    displayName: 'deploy container app'
    timeoutInMinutes: 10
    dependsOn: build
    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.azdoEnv }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: BWA
          - template: 'hearye-server-tasks-deploy.yml'
            parameters:
              azureSubscription: ${{ parameters.azureSubscription }} # AzDO will not allow a variable for this field in the task
              kvName: ${{ parameters.kvName }}
              apiName: ${{ parameters.apiName }}
              resourceGroup: ${{ parameters.resourceGroup }}
              buildId: ${{ parameters.buildId }}